<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.6*" />
    <PackageReference Include="TUnit.Assertions.Should" Version="1.61.29-beta" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GodotGadgets\GodotGadgets.csproj" />
  </ItemGroup>

</Project>
